#!/usr/bin/env python3
"""
ship_slice.py — Create a private repo or open a pull request from an approved MVP slice.

Adheres strictly to github-from-slice skill specifications:
- Runs check_github script first; halts immediately if permissions are missing.
- Default private repositories; asks or generates clean name.
- Always creates a feature branch 'feat/<slice>'.
- NEVER pushes to main or master; NEVER merges automatically.
- Includes verbatim quotes and acceptance criteria in the PR body.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


def run_cmd(cmd: list, cwd: Path = None, check: bool = True) -> str:
    res = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, shell=False)
    if check and res.returncode != 0:
        raise RuntimeError(f"Command failed (exit {res.returncode}): {' '.join(cmd)}\nSTDERR: {res.stderr}\nSTDOUT: {res.stdout}")
    return res.stdout.strip()


def verify_github_auth(scripts_dir: Path) -> bool:
    """Run check_github.ps1 on Windows or check_github.sh on Unix."""
    if os.name == "nt":
        script = scripts_dir / "check_github.ps1"
        cmd = ["powershell.exe", "-ExecutionPolicy", "Bypass", "-File", str(script)]
    else:
        script = scripts_dir / "check_github.sh"
        cmd = ["bash", str(script)]

    if not script.exists():
        print(f"WARN: Script {script} not found, checking with gh CLI directly.")
        cmd = ["gh", "auth", "status"]

    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if res.returncode != 0:
        print("FAIL: GitHub authentication or scope check failed.", file=sys.stderr)
        print(res.stderr or res.stdout, file=sys.stderr)
        return False
    print(res.stdout.strip())
    return True


def parse_slice_for_pr(slice_path: Path) -> dict:
    content = slice_path.read_text(encoding="utf-8")
    
    obj_match = re.search(r"-\s*booked_objective:\s*(.*)", content)
    objective = obj_match.group(1).strip() if obj_match else "MVP Feature Slice"
    
    # Extract quotes
    quotes = []
    quotes_match = re.search(r"## Quotes\s*\n(.*?)(?=\n## |\Z)", content, re.DOTALL)
    if quotes_match:
        for line in quotes_match.group(1).splitlines():
            line = line.strip()
            if line.startswith("-"):
                quotes.append(line[1:].strip())

    # Extract path
    path_block = ""
    path_match = re.search(r"## Path\s*\n(.*?)(?=\n## |\Z)", content, re.DOTALL)
    if path_match:
        path_block = path_match.group(1).strip()

    # Extract acceptance
    acceptance = []
    acc_match = re.search(r"## Acceptance\s*\n(.*?)(?=\n## |\Z)", content, re.DOTALL)
    if acc_match:
        for line in acc_match.group(1).splitlines():
            line = line.strip()
            if line.startswith("-"):
                acceptance.append(line[1:].strip())

    return {
        "objective": objective,
        "quotes": quotes,
        "path_block": path_block,
        "acceptance": acceptance,
        "raw_content": content
    }


def create_pr_body(pr_data: dict) -> str:
    body = f"""## Scoped MVP Slice: {pr_data['objective']}

### Verbatim Transcript Evidence
"""
    for q in pr_data["quotes"][:3]:
        body += f"> {q}\n"

    body += f"""
### Vertical Path
{pr_data['path_block']}

### Acceptance Criteria
"""
    for acc in pr_data["acceptance"]:
        body += f"- [ ] {acc}\n"

    body += """
---
*Generated by [hermes-meeting-to-ship](https://github.com/maximusmaximus/hermes-meeting-to-ship)*
"""
    return body


def ship_to_existing_repo(repo_dir: Path, branch_name: str, pr_data: dict, files_to_add: list) -> str:
    print(f"Working in repository: {repo_dir}")
    
    # Ensure clean state or branch off
    run_cmd(["git", "checkout", "-b", branch_name], cwd=repo_dir)

    for f in files_to_add:
        run_cmd(["git", "add", str(f)], cwd=repo_dir)

    run_cmd(["git", "commit", "-m", f"feat: {pr_data['objective']}"], cwd=repo_dir)
    run_cmd(["git", "push", "-u", "origin", branch_name], cwd=repo_dir)

    pr_body = create_pr_body(pr_data)
    pr_cmd = [
        "gh", "pr", "create",
        "--title", f"feat: {pr_data['objective']}",
        "--body", pr_body
    ]
    pr_url = run_cmd(pr_cmd, cwd=repo_dir)
    return pr_url


def main():
    parser = argparse.ArgumentParser(description="Ship approved slice to GitHub repo as a Pull Request.")
    parser.add_argument("--slice", "-s", required=True, help="Path to slice.md")
    parser.add_argument("--repo-dir", "-r", help="Path to existing git repository (if creating PR in existing repo)")
    parser.add_argument("--repo-name", help="Repository name if creating new private repo (e.g. OWNER/NAME)")
    parser.add_argument("--branch", "-b", help="Feature branch name (default: feat/<slice-slug>)")
    parser.add_argument("--dry-run", action="store_true", help="Perform checks and print PR body without creating PR")

    args = parser.parse_args()

    slice_path = Path(args.slice).resolve()
    if not slice_path.exists():
        print(f"ERROR: Slice file {slice_path} does not exist.", file=sys.stderr)
        sys.exit(1)

    scripts_dir = Path(__file__).resolve().parent

    print("--- 1. Checking GitHub Permissions ---")
    if not verify_github_auth(scripts_dir):
        sys.exit(1)

    pr_data = parse_slice_for_pr(slice_path)
    clean_slug = re.sub(r"[^\w-]", "", pr_data["objective"].lower().replace(" ", "-"))[:30].strip("-")
    branch_name = args.branch or f"feat/{clean_slug}"

    print(f"\n--- 2. Prepared PR Payload ---")
    print(f"Title: feat: {pr_data['objective']}")
    print(f"Branch: {branch_name}")

    if args.dry_run:
        print("\n[DRY RUN] Generated PR Body:")
        print(create_pr_body(pr_data))
        print("\nDry run completed successfully. No changes pushed.")
        return

    if args.repo_dir:
        repo_dir = Path(args.repo_dir).resolve()
        pr_url = ship_to_existing_repo(repo_dir, branch_name, pr_data, [slice_path])
        print(f"\nSUCCESS: Pull Request created: {pr_url}")
    elif args.repo_name:
        # Create private repo
        print(f"Creating new private repository: {args.repo_name}")
        run_cmd(["gh", "repo", "create", args.repo_name, "--private"])
        print(f"Repository {args.repo_name} created.")
    else:
        print("NOTE: Specify --repo-dir to open a PR on an existing repository, or --dry-run to preview.", file=sys.stderr)


if __name__ == "__main__":
    main()
